tunnel: notionmcp
credentials-file: /etc/cloudflared/notionmcp.json

ingress:
  - hostname: notionmcp.nowhere-else.co.uk
    service: http://api:3333
    originRequest:
      noTLSVerify: true
      disableChunkedEncoding: false
  - service: http_status:404


